# Generated by Codex on 2026-01-31

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import common.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0019_alter_asset_connectivity'),
        ('accounts', '0007_alter_account_connectivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretRotationPolicy',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('accounts', models.JSONField(default=list, verbose_name='Account usernames')),
                ('secret_type', models.CharField(choices=[
                    ('password', 'Password'),
                    ('ssh_key', 'SSH key'),
                    ('access_key', 'Access key'),
                    ('token', 'Token'),
                    ('api_key', 'API key')
                ], default='password', max_length=16, verbose_name='Secret type')),
                ('secret_strategy', models.CharField(choices=[
                    ('specific', 'Specific secret'),
                    ('random', 'Random generate')
                ], default='random', max_length=16, verbose_name='Secret strategy')),
                ('secret', common.db.fields.EncryptTextField(blank=True, null=True, verbose_name='Secret')),
                ('password_rules', models.JSONField(default=dict, verbose_name='Password rules')),
                ('ssh_key_change_strategy', models.CharField(choices=[
                    ('set_jms', 'Replace (Replace only keys pushed by JumpServer) '),
                    ('set', 'Empty and append SSH KEY')
                ], default='set_jms', max_length=16, verbose_name='SSH key change strategy')),
                ('check_conn_after_change', models.BooleanField(default=True, verbose_name='Check connection after change')),
                ('params', models.JSONField(default=dict, verbose_name='Parameters')),
                ('interval_hours', models.PositiveIntegerField(default=24, verbose_name='Interval hours')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='First run after')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Next run at')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Last run at')),
            ],
            options={
                'verbose_name': 'Secret rotation policy',
                'ordering': ('-date_created',),
                'unique_together': {('org_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SecretRotationJob',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('status', models.CharField(choices=[
                    ('ready', 'Ready'),
                    ('pending', 'Pending'),
                    ('running', 'Running'),
                    ('success', 'Success'),
                    ('failed', 'Failed'),
                    ('error', 'Error'),
                    ('canceled', 'Canceled')
                ], default='pending', max_length=16, verbose_name='Status')),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('timing', 'Timing')], default='manual', max_length=16, verbose_name='Trigger')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended at')),
                ('summary', models.JSONField(default=dict, verbose_name='Summary')),
                ('error', models.TextField(blank=True, default='', verbose_name='Error message')),
                ('snapshot', models.JSONField(default=dict, verbose_name='Payload snapshot')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_jobs', to='accounts.automationexecution', verbose_name='Automation execution')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.secretrotationpolicy', verbose_name='Policy')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_rotation_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
            ],
            options={
                'verbose_name': 'Secret rotation job',
                'ordering': ('-date_created',),
            },
        ),
        migrations.AddField(
            model_name='secretrotationpolicy',
            name='assets',
            field=models.ManyToManyField(blank=True, to='assets.asset', verbose_name='Assets'),
        ),
        migrations.AddField(
            model_name='secretrotationpolicy',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='assets.node', verbose_name='Nodes'),
        ),
        migrations.AddField(
            model_name='secretrotationpolicy',
            name='recipients',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Recipients'),
        ),
    ]
