# Generated by Codex on 2026-01-31

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0019_alter_asset_connectivity'),
        ('accounts', '0008_secret_rotation_policy_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('engine', models.CharField(max_length=64, verbose_name='Engine')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16, verbose_name='Severity')),
                ('conditions', models.JSONField(default=dict, verbose_name='Conditions')),
                ('accounts', models.JSONField(default=list, verbose_name='Account usernames', blank=True)),
                ('interval_hours', models.PositiveIntegerField(default=24, verbose_name='Interval hours')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='First run after')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Next run at')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Last run at')),
            ],
            options={
                'verbose_name': 'Risk rule',
                'ordering': ('-date_created',),
                'unique_together': {('org_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RiskFinding',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='Fingerprint')),
                ('status', models.CharField(choices=[('open', 'Open'), ('ignored', 'Ignored'), ('resolved', 'Resolved')], default='open', max_length=16, verbose_name='Status')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='First seen')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Last seen')),
                ('evidence', models.JSONField(default=dict, verbose_name='Evidence')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16, verbose_name='Severity')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_findings', to='accounts.account', verbose_name='Account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_findings', to='assets.asset', verbose_name='Asset')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='accounts.riskrule', verbose_name='Rule')),
            ],
            options={
                'verbose_name': 'Risk finding',
                'ordering': ('-last_seen',),
                'unique_together': {('rule', 'fingerprint')},
            },
        ),
        migrations.AddField(
            model_name='riskrule',
            name='assets',
            field=models.ManyToManyField(blank=True, to='assets.asset', verbose_name='Assets'),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='assets.node', verbose_name='Nodes'),
        ),
    ]
